OFFICIAL_TOUR_IMAGE_URL = (
    "https://www.brunomars.com/sites/g/files/g2000021861/files/2026-03/"
    "BrunoTheRomanticTour_Creative10_1080x1440hetvdvre.jpg"
)

OFFICIAL_TOUR_DESCRIPTION = "Official Bruno Mars tour date."

DEFAULT_TICKET_SETUP = [
    {"type": "vip", "price_usd": 5000.0, "available_quantity": 100, "total_quantity": 100},
    {"type": "meetgreet", "price_usd": 15000.0, "available_quantity": 25, "total_quantity": 25},
    {"type": "backstage", "price_usd": 35000.0, "available_quantity": 10, "total_quantity": 10},
    {"type": "soundcheck", "price_usd": 8500.0, "available_quantity": 40, "total_quantity": 40},
    {"type": "photoop", "price_usd": 20000.0, "available_quantity": 20, "total_quantity": 20},
    {"type": "aftershow", "price_usd": 50000.0, "available_quantity": 12, "total_quantity": 12},
    {"type": "hospitality", "price_usd": 150000.0, "available_quantity": 8, "total_quantity": 8},
    {"type": "birthday", "price_usd": 250000.0, "available_quantity": 6, "total_quantity": 6},
    {"type": "corporate", "price_usd": 500000.0, "available_quantity": 4, "total_quantity": 4},
    {"type": "privatemeetup", "price_usd": 1000000.0, "available_quantity": 2, "total_quantity": 2},
]

OFFICIAL_TOUR_SCHEDULE = [
    {"date": "2026-04-10", "venue": "Allegiant Stadium", "city": "Las Vegas, NV"},
    {"date": "2026-04-11", "venue": "Allegiant Stadium", "city": "Las Vegas, NV"},
    {"date": "2026-04-14", "venue": "State Farm Stadium", "city": "Glendale, AZ"},
    {"date": "2026-04-15", "venue": "State Farm Stadium", "city": "Glendale, AZ"},
    {"date": "2026-04-18", "venue": "Globe Life Field", "city": "Arlington, TX"},
    {"date": "2026-04-19", "venue": "Globe Life Field", "city": "Arlington, TX"},
    {"date": "2026-04-22", "venue": "NRG Stadium", "city": "Houston, TX"},
    {"date": "2026-04-25", "venue": "Bobby Dodd Stadium at Hyundai Field", "city": "Atlanta, GA"},
    {"date": "2026-04-26", "venue": "Bobby Dodd Stadium at Hyundai Field", "city": "Atlanta, GA"},
    {"date": "2026-04-29", "venue": "Bank of America Stadium", "city": "Charlotte, NC"},
    {"date": "2026-05-02", "venue": "Northwest Stadium", "city": "Landover, MD"},
    {"date": "2026-05-03", "venue": "Northwest Stadium", "city": "Landover, MD"},
    {"date": "2026-05-06", "venue": "Nissan Stadium", "city": "Nashville, TN"},
    {"date": "2026-05-09", "venue": "Ford Field", "city": "Detroit, MI"},
    {"date": "2026-05-10", "venue": "Ford Field", "city": "Detroit, MI"},
    {"date": "2026-05-13", "venue": "U.S. Bank Stadium", "city": "Minneapolis, MN"},
    {"date": "2026-05-16", "venue": "Soldier Field Stadium", "city": "Chicago, IL"},
    {"date": "2026-05-17", "venue": "Soldier Field Stadium", "city": "Chicago, IL"},
    {"date": "2026-05-20", "venue": "Ohio Stadium", "city": "Columbus, OH"},
    {"date": "2026-05-23", "venue": "Rogers Stadium", "city": "Toronto, ON"},
    {"date": "2026-05-24", "venue": "Rogers Stadium", "city": "Toronto, ON"},
    {"date": "2026-05-27", "venue": "Rogers Stadium", "city": "Toronto, ON"},
    {"date": "2026-05-28", "venue": "Rogers Stadium", "city": "Toronto, ON"},
    {"date": "2026-05-30", "venue": "Rogers Stadium", "city": "Toronto, ON"},
    {"date": "2026-06-18", "venue": "Stade de France", "city": "Paris, FR"},
    {"date": "2026-06-20", "venue": "Stade de France", "city": "Paris, FR"},
    {"date": "2026-06-21", "venue": "Stade de France", "city": "Paris, FR"},
    {"date": "2026-06-26", "venue": "Olympiastadion", "city": "Berlin, DE"},
    {"date": "2026-06-28", "venue": "Olympiastadion", "city": "Berlin, DE"},
    {"date": "2026-06-29", "venue": "Olympiastadion", "city": "Berlin, DE"},
    {"date": "2026-07-02", "venue": "Johan Cruijff ArenA", "city": "Amsterdam, NL"},
    {"date": "2026-07-04", "venue": "Johan Cruijff ArenA", "city": "Amsterdam, NL"},
    {"date": "2026-07-05", "venue": "Johan Cruijff ArenA", "city": "Amsterdam, NL"},
    {"date": "2026-07-07", "venue": "Johan Cruijff ArenA", "city": "Amsterdam, NL"},
    {"date": "2026-07-10", "venue": "Riyadh Air Metropolitano", "city": "Madrid, ES"},
    {"date": "2026-07-11", "venue": "Riyadh Air Metropolitano", "city": "Madrid, ES"},
    {"date": "2026-07-14", "venue": "Stadio San Siro", "city": "Milan, IT"},
    {"date": "2026-07-15", "venue": "Stadio San Siro", "city": "Milan, IT"},
    {"date": "2026-07-18", "venue": "Wembley Stadium Connected by EE", "city": "London, UK"},
    {"date": "2026-07-19", "venue": "Wembley Stadium Connected by EE", "city": "London, UK"},
    {"date": "2026-07-22", "venue": "Wembley Stadium Connected by EE", "city": "London, UK"},
    {"date": "2026-07-24", "venue": "Wembley Stadium Connected by EE", "city": "London, UK"},
    {"date": "2026-07-25", "venue": "Wembley Stadium Connected by EE", "city": "London, UK"},
    {"date": "2026-07-28", "venue": "Wembley Stadium Connected by EE", "city": "London, UK"},
    {"date": "2026-08-21", "venue": "Metlife Stadium", "city": "East Rutherford, NJ"},
    {"date": "2026-08-22", "venue": "Metlife Stadium", "city": "East Rutherford, NJ"},
    {"date": "2026-08-25", "venue": "Metlife Stadium", "city": "East Rutherford, NJ"},
    {"date": "2026-08-26", "venue": "MetLife Stadium", "city": "East Rutherford, NJ"},
    {"date": "2026-08-29", "venue": "Acrisure Stadium", "city": "Pittsburgh, PA"},
    {"date": "2026-09-01", "venue": "Lincoln Financial Field", "city": "Philadelphia, PA"},
    {"date": "2026-09-02", "venue": "Lincoln Financial Field", "city": "Philadelphia, PA"},
    {"date": "2026-09-05", "venue": "Gillette Stadium", "city": "Foxborough, MA"},
    {"date": "2026-09-06", "venue": "Gillette Stadium", "city": "Foxborough, MA"},
    {"date": "2026-09-09", "venue": "Lucas Oil Stadium", "city": "Indianapolis, IN"},
    {"date": "2026-09-12", "venue": "Raymond James Stadium", "city": "Tampa, FL"},
    {"date": "2026-09-13", "venue": "Raymond James Stadium", "city": "Tampa, FL"},
    {"date": "2026-09-16", "venue": "Caesars Superdome", "city": "New Orleans, LA"},
    {"date": "2026-09-19", "venue": "Hard Rock Stadium", "city": "Miami, FL"},
    {"date": "2026-09-20", "venue": "Hard Rock Stadium", "city": "Miami, FL"},
    {"date": "2026-09-23", "venue": "Alamodome", "city": "San Antonio, TX"},
    {
        "date": "2026-09-26",
        "venue": "Falcon Stadium at the United States Air Force Academy",
        "city": "Air Force Academy, CO",
    },
    {
        "date": "2026-09-27",
        "venue": "Falcon Stadium at the United States Air Force Academy",
        "city": "Air Force Academy, CO",
    },
    {"date": "2026-09-30", "venue": "SoFi Stadium", "city": "Los Angeles, CA"},
    {"date": "2026-10-02", "venue": "SoFi Stadium", "city": "Los Angeles, CA"},
    {"date": "2026-10-03", "venue": "SoFi Stadium", "city": "Los Angeles, CA"},
    {"date": "2026-10-06", "venue": "SoFi Stadium", "city": "Los Angeles, CA"},
    {"date": "2026-10-07", "venue": "SoFi Stadium", "city": "Los Angeles, CA"},
    {"date": "2026-10-10", "venue": "Levi's Stadium", "city": "Santa Clara, CA"},
    {"date": "2026-10-11", "venue": "Levi's Stadium", "city": "Santa Clara, CA"},
    {"date": "2026-10-14", "venue": "BC Place", "city": "Vancouver, BC"},
    {"date": "2026-10-16", "venue": "BC Place", "city": "Vancouver, BC"},
    {"date": "2026-10-17", "venue": "BC Place", "city": "Vancouver, BC"},
    {"date": "2026-10-20", "venue": "BC Place", "city": "Vancouver, BC"},
    {"date": "2026-10-21", "venue": "BC Place Stadium", "city": "Vancouver, BC"},
    {"date": "2026-12-03", "venue": "Estadio GNP Seguros", "city": "Mexico City, MX"},
    {"date": "2026-12-04", "venue": "Estadio GNP Seguros", "city": "Mexico City, MX"},
    {"date": "2026-12-07", "venue": "Estadio GNP Seguros", "city": "Mexico City, MX"},
    {"date": "2026-12-08", "venue": "Estadio GNP Seguros", "city": "Mexico City, MX"},
]
